name: cesm-timeseries-dev
channels:
    - conda-forge
    - pyviz
    - ncar
    - nodefaults
dependencies:
    - bokeh
    - bottleneck
    - prefect
    - intake-esm
    - xarray
    - dask
    - hvplot
    - holoviews
    - panel
    - regionmask
    - geocat-comp
    
